/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#324a5f',
        'primary-container': '#4a6278',
        'on-primary-container': '#c4ddf7',
        'primary-fixed': '#cce5ff',
        'primary-fixed-dim': '#b0c9e3',
        'on-primary-fixed': '#011d31',
        'on-primary-fixed-variant': '#31495e',
        'secondary': '#595f66',
        'secondary-container': '#dde3eb',
        'secondary-fixed': '#dde3eb',
        'secondary-fixed-dim': '#c1c7cf',
        'surface': '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-container': '#e7eeff',
        'surface-container-low': '#f0f3ff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#496177',
        'surface-variant': '#d8e3fb',
        'background': '#f9f9ff',
        'on-background': '#111c2d',
        'on-surface': '#111c2d',
        'on-surface-variant': '#43474c',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'outline': '#73777d',
        'outline-variant': '#c3c7cd',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      fontFamily: {
        'display': ['Plus Jakarta Sans', 'sans-serif'],
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Atkinson Hyperlegible Next', 'sans-serif'],
        'label': ['Atkinson Hyperlegible Next', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '400' }],
        'body-md': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
